package u5;

/* compiled from: r8-map-id-7bd85f1e2f7c008961cee9e44e2adc91279c207f1e1906d6942eb2d5ada0c5e8 */
/* loaded from: classes.dex */
public abstract class u {

    /* renamed from: a, reason: collision with root package name */
    public static final b f12920a;

    /* renamed from: b, reason: collision with root package name */
    public static final b f12921b;

    /* renamed from: c, reason: collision with root package name */
    public static final b f12922c;

    /* renamed from: d, reason: collision with root package name */
    public static final b f12923d;

    /* renamed from: e, reason: collision with root package name */
    public static final b f12924e;

    static {
        new b(0, "VISUAL_STATE_CALLBACK", "VISUAL_STATE_CALLBACK");
        new b(0, "OFF_SCREEN_PRERASTER", "OFF_SCREEN_PRERASTER");
        new b(3, "SAFE_BROWSING_ENABLE", "SAFE_BROWSING_ENABLE");
        new b(1, "DISABLED_ACTION_MODE_MENU_ITEMS", "DISABLED_ACTION_MODE_MENU_ITEMS");
        new b(4, "START_SAFE_BROWSING", "START_SAFE_BROWSING");
        new b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_WHITELIST");
        new b(4, "SAFE_BROWSING_WHITELIST", "SAFE_BROWSING_ALLOWLIST");
        new b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_WHITELIST");
        new b(4, "SAFE_BROWSING_ALLOWLIST", "SAFE_BROWSING_ALLOWLIST");
        new b(4, "SAFE_BROWSING_PRIVACY_POLICY_URL", "SAFE_BROWSING_PRIVACY_POLICY_URL");
        new b(1, "SERVICE_WORKER_BASIC_USAGE", "SERVICE_WORKER_BASIC_USAGE");
        new b(1, "SERVICE_WORKER_CACHE_MODE", "SERVICE_WORKER_CACHE_MODE");
        new b(1, "SERVICE_WORKER_CONTENT_ACCESS", "SERVICE_WORKER_CONTENT_ACCESS");
        new b(1, "SERVICE_WORKER_FILE_ACCESS", "SERVICE_WORKER_FILE_ACCESS");
        new b(1, "SERVICE_WORKER_BLOCK_NETWORK_LOADS", "SERVICE_WORKER_BLOCK_NETWORK_LOADS");
        new b(1, "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST", "SERVICE_WORKER_SHOULD_INTERCEPT_REQUEST");
        new b(0, "RECEIVE_WEB_RESOURCE_ERROR", "RECEIVE_WEB_RESOURCE_ERROR");
        new b(0, "RECEIVE_HTTP_ERROR", "RECEIVE_HTTP_ERROR");
        new b(1, "SHOULD_OVERRIDE_WITH_REDIRECTS", "SHOULD_OVERRIDE_WITH_REDIRECTS");
        new b(4, "SAFE_BROWSING_HIT", "SAFE_BROWSING_HIT");
        new b(1, "WEB_RESOURCE_REQUEST_IS_REDIRECT", "WEB_RESOURCE_REQUEST_IS_REDIRECT");
        f12920a = new b(0, "WEB_RESOURCE_ERROR_GET_DESCRIPTION", "WEB_RESOURCE_ERROR_GET_DESCRIPTION");
        f12921b = new b(0, "WEB_RESOURCE_ERROR_GET_CODE", "WEB_RESOURCE_ERROR_GET_CODE");
        new b(4, "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY", "SAFE_BROWSING_RESPONSE_BACK_TO_SAFETY");
        new b(4, "SAFE_BROWSING_RESPONSE_PROCEED", "SAFE_BROWSING_RESPONSE_PROCEED");
        f12922c = new b(4, "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL", "SAFE_BROWSING_RESPONSE_SHOW_INTERSTITIAL");
        new b(0, "WEB_MESSAGE_PORT_POST_MESSAGE", "WEB_MESSAGE_PORT_POST_MESSAGE");
        new b(0, "WEB_MESSAGE_PORT_CLOSE", "WEB_MESSAGE_PORT_CLOSE");
        f12923d = new b(2, "WEB_MESSAGE_GET_MESSAGE_PAYLOAD", "WEB_MESSAGE_GET_MESSAGE_PAYLOAD");
        new b(0, "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK", "WEB_MESSAGE_PORT_SET_MESSAGE_CALLBACK");
        new b(0, "CREATE_WEB_MESSAGE_CHANNEL", "CREATE_WEB_MESSAGE_CHANNEL");
        new b(0, "POST_WEB_MESSAGE", "POST_WEB_MESSAGE");
        new b(0, "WEB_MESSAGE_CALLBACK_ON_MESSAGE", "WEB_MESSAGE_CALLBACK_ON_MESSAGE");
        new b(3, "GET_WEB_VIEW_CLIENT", "GET_WEB_VIEW_CLIENT");
        new b(3, "GET_WEB_CHROME_CLIENT", "GET_WEB_CHROME_CLIENT");
        new b(6, "GET_WEB_VIEW_RENDERER", "GET_WEB_VIEW_RENDERER");
        new b(6, "WEB_VIEW_RENDERER_TERMINATE", "WEB_VIEW_RENDERER_TERMINATE");
        new b(5, "TRACING_CONTROLLER_BASIC_USAGE", "TRACING_CONTROLLER_BASIC_USAGE");
        q.f12914a.add(new Object());
        new b(6, "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE", "WEB_VIEW_RENDERER_CLIENT_BASIC_USAGE");
        new t();
        new b(2, "PROXY_OVERRIDE", "PROXY_OVERRIDE:3");
        new b(2, "SUPPRESS_ERROR_PAGE", "SUPPRESS_ERROR_PAGE");
        new b(2, "MULTI_PROCESS", "MULTI_PROCESS_QUERY");
        new b(6, "FORCE_DARK", "FORCE_DARK");
        new b(2, "FORCE_DARK_STRATEGY", "FORCE_DARK_BEHAVIOR");
        f12924e = new b(2, "WEB_MESSAGE_LISTENER", "WEB_MESSAGE_LISTENER");
        new b(2, "DOCUMENT_START_SCRIPT", "DOCUMENT_START_SCRIPT:1");
        new b(2, "PROXY_OVERRIDE_REVERSE_BYPASS", "PROXY_OVERRIDE_REVERSE_BYPASS");
        new b(2, "GET_VARIATIONS_HEADER", "GET_VARIATIONS_HEADER");
        new b(2, "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY", "ENTERPRISE_AUTHENTICATION_APP_LINK_POLICY");
        new b(2, "GET_COOKIE_INFO", "GET_COOKIE_INFO");
        new b(2, "REQUESTED_WITH_HEADER_ALLOW_LIST", "REQUESTED_WITH_HEADER_ALLOW_LIST");
    }
}
