package t9;

import android.R;

/* loaded from: classes.dex */
public abstract class a {

    /* renamed from: a, reason: collision with root package name */
    public static final int[] f12673a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, com.playfy.tv.R.attr.elevation, com.playfy.tv.R.attr.expanded, com.playfy.tv.R.attr.liftOnScroll, com.playfy.tv.R.attr.liftOnScrollColor, com.playfy.tv.R.attr.liftOnScrollTargetViewId, com.playfy.tv.R.attr.statusBarForeground};

    /* renamed from: b, reason: collision with root package name */
    public static final int[] f12674b = {com.playfy.tv.R.attr.layout_scrollEffect, com.playfy.tv.R.attr.layout_scrollFlags, com.playfy.tv.R.attr.layout_scrollInterpolator};

    /* renamed from: c, reason: collision with root package name */
    public static final int[] f12675c = {com.playfy.tv.R.attr.autoAdjustToWithinGrandparentBounds, com.playfy.tv.R.attr.backgroundColor, com.playfy.tv.R.attr.badgeFixedEdge, com.playfy.tv.R.attr.badgeGravity, com.playfy.tv.R.attr.badgeHeight, com.playfy.tv.R.attr.badgeRadius, com.playfy.tv.R.attr.badgeShapeAppearance, com.playfy.tv.R.attr.badgeShapeAppearanceOverlay, com.playfy.tv.R.attr.badgeText, com.playfy.tv.R.attr.badgeTextAppearance, com.playfy.tv.R.attr.badgeTextColor, com.playfy.tv.R.attr.badgeVerticalPadding, com.playfy.tv.R.attr.badgeWidePadding, com.playfy.tv.R.attr.badgeWidth, com.playfy.tv.R.attr.badgeWithTextHeight, com.playfy.tv.R.attr.badgeWithTextRadius, com.playfy.tv.R.attr.badgeWithTextShapeAppearance, com.playfy.tv.R.attr.badgeWithTextShapeAppearanceOverlay, com.playfy.tv.R.attr.badgeWithTextWidth, com.playfy.tv.R.attr.horizontalOffset, com.playfy.tv.R.attr.horizontalOffsetWithText, com.playfy.tv.R.attr.largeFontVerticalOffsetAdjustment, com.playfy.tv.R.attr.maxCharacterCount, com.playfy.tv.R.attr.maxNumber, com.playfy.tv.R.attr.number, com.playfy.tv.R.attr.offsetAlignmentMode, com.playfy.tv.R.attr.verticalOffset, com.playfy.tv.R.attr.verticalOffsetWithText};

    /* renamed from: d, reason: collision with root package name */
    public static final int[] f12676d = {R.attr.indeterminate, com.playfy.tv.R.attr.hideAnimationBehavior, com.playfy.tv.R.attr.indeterminateAnimatorDurationScale, com.playfy.tv.R.attr.indicatorColor, com.playfy.tv.R.attr.indicatorTrackGapSize, com.playfy.tv.R.attr.minHideDelay, com.playfy.tv.R.attr.showAnimationBehavior, com.playfy.tv.R.attr.showDelay, com.playfy.tv.R.attr.trackColor, com.playfy.tv.R.attr.trackCornerRadius, com.playfy.tv.R.attr.trackThickness, com.playfy.tv.R.attr.waveAmplitude, com.playfy.tv.R.attr.waveSpeed, com.playfy.tv.R.attr.wavelength, com.playfy.tv.R.attr.wavelengthDeterminate, com.playfy.tv.R.attr.wavelengthIndeterminate};

    /* renamed from: e, reason: collision with root package name */
    public static final int[] f12677e = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.behavior_draggable, com.playfy.tv.R.attr.behavior_draggableOnNestedScroll, com.playfy.tv.R.attr.behavior_expandedOffset, com.playfy.tv.R.attr.behavior_fitToContents, com.playfy.tv.R.attr.behavior_halfExpandedRatio, com.playfy.tv.R.attr.behavior_hideable, com.playfy.tv.R.attr.behavior_peekHeight, com.playfy.tv.R.attr.behavior_saveFlags, com.playfy.tv.R.attr.behavior_significantVelocityThreshold, com.playfy.tv.R.attr.behavior_skipCollapsed, com.playfy.tv.R.attr.gestureInsetBottomIgnored, com.playfy.tv.R.attr.marginLeftSystemWindowInsets, com.playfy.tv.R.attr.marginRightSystemWindowInsets, com.playfy.tv.R.attr.marginTopSystemWindowInsets, com.playfy.tv.R.attr.paddingBottomSystemWindowInsets, com.playfy.tv.R.attr.paddingLeftSystemWindowInsets, com.playfy.tv.R.attr.paddingRightSystemWindowInsets, com.playfy.tv.R.attr.paddingTopSystemWindowInsets, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.shouldRemoveExpandedCorners};

    /* renamed from: f, reason: collision with root package name */
    public static final int[] f12678f = {com.playfy.tv.R.attr.carousel_alignment, com.playfy.tv.R.attr.carousel_backwardTransition, com.playfy.tv.R.attr.carousel_emptyViewsBehavior, com.playfy.tv.R.attr.carousel_firstView, com.playfy.tv.R.attr.carousel_forwardTransition, com.playfy.tv.R.attr.carousel_infinite, com.playfy.tv.R.attr.carousel_nextState, com.playfy.tv.R.attr.carousel_previousState, com.playfy.tv.R.attr.carousel_touchUpMode, com.playfy.tv.R.attr.carousel_touchUp_dampeningFactor, com.playfy.tv.R.attr.carousel_touchUp_velocityThreshold};

    /* renamed from: g, reason: collision with root package name */
    public static final int[] f12679g = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, com.playfy.tv.R.attr.checkedIcon, com.playfy.tv.R.attr.checkedIconEnabled, com.playfy.tv.R.attr.checkedIconTint, com.playfy.tv.R.attr.checkedIconVisible, com.playfy.tv.R.attr.chipBackgroundColor, com.playfy.tv.R.attr.chipCornerRadius, com.playfy.tv.R.attr.chipEndPadding, com.playfy.tv.R.attr.chipIcon, com.playfy.tv.R.attr.chipIconEnabled, com.playfy.tv.R.attr.chipIconSize, com.playfy.tv.R.attr.chipIconTint, com.playfy.tv.R.attr.chipIconVisible, com.playfy.tv.R.attr.chipMinHeight, com.playfy.tv.R.attr.chipMinTouchTargetSize, com.playfy.tv.R.attr.chipStartPadding, com.playfy.tv.R.attr.chipStrokeColor, com.playfy.tv.R.attr.chipStrokeWidth, com.playfy.tv.R.attr.chipSurfaceColor, com.playfy.tv.R.attr.closeIcon, com.playfy.tv.R.attr.closeIconEnabled, com.playfy.tv.R.attr.closeIconEndPadding, com.playfy.tv.R.attr.closeIconSize, com.playfy.tv.R.attr.closeIconStartPadding, com.playfy.tv.R.attr.closeIconTint, com.playfy.tv.R.attr.closeIconVisible, com.playfy.tv.R.attr.ensureMinTouchTargetSize, com.playfy.tv.R.attr.hideMotionSpec, com.playfy.tv.R.attr.iconEndPadding, com.playfy.tv.R.attr.iconStartPadding, com.playfy.tv.R.attr.rippleColor, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.showMotionSpec, com.playfy.tv.R.attr.textEndPadding, com.playfy.tv.R.attr.textStartPadding};

    /* renamed from: h, reason: collision with root package name */
    public static final int[] f12680h = {com.playfy.tv.R.attr.checkedChip, com.playfy.tv.R.attr.chipSpacing, com.playfy.tv.R.attr.chipSpacingHorizontal, com.playfy.tv.R.attr.chipSpacingVertical, com.playfy.tv.R.attr.selectionRequired, com.playfy.tv.R.attr.singleLine, com.playfy.tv.R.attr.singleSelection};

    /* renamed from: i, reason: collision with root package name */
    public static final int[] f12681i = {com.playfy.tv.R.attr.indeterminateAnimationTypeCircular, com.playfy.tv.R.attr.indeterminateTrackVisible, com.playfy.tv.R.attr.indicatorDirectionCircular, com.playfy.tv.R.attr.indicatorInset, com.playfy.tv.R.attr.indicatorSize};
    public static final int[] j = {com.playfy.tv.R.attr.clockFaceBackgroundColor, com.playfy.tv.R.attr.clockNumberTextColor};

    /* renamed from: k, reason: collision with root package name */
    public static final int[] f12682k = {com.playfy.tv.R.attr.clockHandColor, com.playfy.tv.R.attr.materialCircleRadius, com.playfy.tv.R.attr.selectorSize};

    /* renamed from: l, reason: collision with root package name */
    public static final int[] f12683l = {com.playfy.tv.R.attr.behavior_autoHide, com.playfy.tv.R.attr.behavior_autoShrink};

    /* renamed from: m, reason: collision with root package name */
    public static final int[] f12684m = {R.attr.enabled, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.backgroundTintMode, com.playfy.tv.R.attr.borderWidth, com.playfy.tv.R.attr.elevation, com.playfy.tv.R.attr.ensureMinTouchTargetSize, com.playfy.tv.R.attr.fabCustomSize, com.playfy.tv.R.attr.fabSize, com.playfy.tv.R.attr.hideMotionSpec, com.playfy.tv.R.attr.hoveredFocusedTranslationZ, com.playfy.tv.R.attr.maxImageSize, com.playfy.tv.R.attr.pressedTranslationZ, com.playfy.tv.R.attr.rippleColor, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.showMotionSpec, com.playfy.tv.R.attr.useCompatPadding};

    /* renamed from: n, reason: collision with root package name */
    public static final int[] f12685n = {com.playfy.tv.R.attr.behavior_autoHide};

    /* renamed from: o, reason: collision with root package name */
    public static final int[] f12686o = {com.playfy.tv.R.attr.horizontalItemSpacing, com.playfy.tv.R.attr.lineSpacing};

    /* renamed from: p, reason: collision with root package name */
    public static final int[] f12687p = {R.attr.foreground, R.attr.foregroundGravity, com.playfy.tv.R.attr.foregroundInsidePadding};

    /* renamed from: q, reason: collision with root package name */
    public static final int[] f12688q = {com.playfy.tv.R.attr.indeterminateAnimationType, com.playfy.tv.R.attr.indicatorDirectionLinear, com.playfy.tv.R.attr.trackInnerCornerRadius, com.playfy.tv.R.attr.trackStopIndicatorPadding, com.playfy.tv.R.attr.trackStopIndicatorSize};

    /* renamed from: r, reason: collision with root package name */
    public static final int[] f12689r = {com.playfy.tv.R.attr.backgroundInsetBottom, com.playfy.tv.R.attr.backgroundInsetEnd, com.playfy.tv.R.attr.backgroundInsetStart, com.playfy.tv.R.attr.backgroundInsetTop, com.playfy.tv.R.attr.backgroundTint};
    public static final int[] s = {R.attr.inputType, R.attr.popupElevation, com.playfy.tv.R.attr.dropDownBackgroundTint, com.playfy.tv.R.attr.simpleItemLayout, com.playfy.tv.R.attr.simpleItemSelectedColor, com.playfy.tv.R.attr.simpleItemSelectedRippleColor, com.playfy.tv.R.attr.simpleItems};

    /* renamed from: t, reason: collision with root package name */
    public static final int[] f12690t = {R.attr.background, R.attr.checked, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.backgroundTintMode, com.playfy.tv.R.attr.cornerRadius, com.playfy.tv.R.attr.elevation, com.playfy.tv.R.attr.icon, com.playfy.tv.R.attr.iconGravity, com.playfy.tv.R.attr.iconPadding, com.playfy.tv.R.attr.iconSize, com.playfy.tv.R.attr.iconTint, com.playfy.tv.R.attr.iconTintMode, com.playfy.tv.R.attr.opticalCenterEnabled, com.playfy.tv.R.attr.rippleColor, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.strokeColor, com.playfy.tv.R.attr.strokeWidth, com.playfy.tv.R.attr.toggleCheckedStateOnClick};

    /* renamed from: u, reason: collision with root package name */
    public static final int[] f12691u = {R.attr.enabled, R.attr.spacing, com.playfy.tv.R.attr.buttonSizeChange, com.playfy.tv.R.attr.innerCornerSize, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay};

    /* renamed from: v, reason: collision with root package name */
    public static final int[] f12692v = {R.attr.enabled, R.attr.spacing, com.playfy.tv.R.attr.checkedButton, com.playfy.tv.R.attr.innerCornerSize, com.playfy.tv.R.attr.selectionRequired, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.singleSelection};

    /* renamed from: w, reason: collision with root package name */
    public static final int[] f12693w = {R.attr.windowFullscreen, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.dayInvalidStyle, com.playfy.tv.R.attr.daySelectedStyle, com.playfy.tv.R.attr.dayStyle, com.playfy.tv.R.attr.dayTodayStyle, com.playfy.tv.R.attr.nestedScrollable, com.playfy.tv.R.attr.rangeFillColor, com.playfy.tv.R.attr.yearSelectedStyle, com.playfy.tv.R.attr.yearStyle, com.playfy.tv.R.attr.yearTodayStyle};

    /* renamed from: x, reason: collision with root package name */
    public static final int[] f12694x = {R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, com.playfy.tv.R.attr.itemFillColor, com.playfy.tv.R.attr.itemShapeAppearance, com.playfy.tv.R.attr.itemShapeAppearanceOverlay, com.playfy.tv.R.attr.itemStrokeColor, com.playfy.tv.R.attr.itemStrokeWidth, com.playfy.tv.R.attr.itemTextColor};

    /* renamed from: y, reason: collision with root package name */
    public static final int[] f12695y = {R.attr.checkable, com.playfy.tv.R.attr.cardForegroundColor, com.playfy.tv.R.attr.checkedIcon, com.playfy.tv.R.attr.checkedIconGravity, com.playfy.tv.R.attr.checkedIconMargin, com.playfy.tv.R.attr.checkedIconSize, com.playfy.tv.R.attr.checkedIconTint, com.playfy.tv.R.attr.rippleColor, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.state_dragged, com.playfy.tv.R.attr.strokeColor, com.playfy.tv.R.attr.strokeWidth};

    /* renamed from: z, reason: collision with root package name */
    public static final int[] f12696z = {R.attr.button, com.playfy.tv.R.attr.buttonCompat, com.playfy.tv.R.attr.buttonIcon, com.playfy.tv.R.attr.buttonIconTint, com.playfy.tv.R.attr.buttonIconTintMode, com.playfy.tv.R.attr.buttonTint, com.playfy.tv.R.attr.centerIfNoTextEnabled, com.playfy.tv.R.attr.checkedState, com.playfy.tv.R.attr.errorAccessibilityLabel, com.playfy.tv.R.attr.errorShown, com.playfy.tv.R.attr.useMaterialThemeColors};
    public static final int[] A = {com.playfy.tv.R.attr.dividerColor, com.playfy.tv.R.attr.dividerInsetEnd, com.playfy.tv.R.attr.dividerInsetStart, com.playfy.tv.R.attr.dividerThickness, com.playfy.tv.R.attr.lastItemDecorated};
    public static final int[] B = {com.playfy.tv.R.attr.buttonTint, com.playfy.tv.R.attr.useMaterialThemeColors};
    public static final int[] C = {com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay};
    public static final int[] D = {com.playfy.tv.R.attr.damping, com.playfy.tv.R.attr.stiffness};
    public static final int[] E = {R.attr.letterSpacing, R.attr.fontVariationSettings, R.attr.lineHeight, com.playfy.tv.R.attr.fontVariationSettings, com.playfy.tv.R.attr.lineHeight};
    public static final int[] F = {R.attr.textAppearance, R.attr.lineHeight, com.playfy.tv.R.attr.lineHeight};
    public static final int[] G = {com.playfy.tv.R.attr.logoAdjustViewBounds, com.playfy.tv.R.attr.logoScaleType, com.playfy.tv.R.attr.navigationIconTint, com.playfy.tv.R.attr.subtitleCentered, com.playfy.tv.R.attr.titleCentered};
    public static final int[] H = {com.playfy.tv.R.attr.materialCircleRadius};
    public static final int[] I = {com.playfy.tv.R.attr.behavior_overlapTop};
    public static final int[] J = {com.playfy.tv.R.attr.cornerFamily, com.playfy.tv.R.attr.cornerFamilyBottomLeft, com.playfy.tv.R.attr.cornerFamilyBottomRight, com.playfy.tv.R.attr.cornerFamilyTopLeft, com.playfy.tv.R.attr.cornerFamilyTopRight, com.playfy.tv.R.attr.cornerSize, com.playfy.tv.R.attr.cornerSizeBottomLeft, com.playfy.tv.R.attr.cornerSizeBottomRight, com.playfy.tv.R.attr.cornerSizeTopLeft, com.playfy.tv.R.attr.cornerSizeTopRight};
    public static final int[] K = {com.playfy.tv.R.attr.contentPadding, com.playfy.tv.R.attr.contentPaddingBottom, com.playfy.tv.R.attr.contentPaddingEnd, com.playfy.tv.R.attr.contentPaddingLeft, com.playfy.tv.R.attr.contentPaddingRight, com.playfy.tv.R.attr.contentPaddingStart, com.playfy.tv.R.attr.contentPaddingTop, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.strokeColor, com.playfy.tv.R.attr.strokeWidth};
    public static final int[] L = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.behavior_draggable, com.playfy.tv.R.attr.coplanarSiblingViewId, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay};
    public static final int[] M = {R.attr.maxWidth, com.playfy.tv.R.attr.actionTextColorAlpha, com.playfy.tv.R.attr.animationMode, com.playfy.tv.R.attr.backgroundOverlayColorAlpha, com.playfy.tv.R.attr.backgroundTint, com.playfy.tv.R.attr.backgroundTintMode, com.playfy.tv.R.attr.elevation, com.playfy.tv.R.attr.maxActionInlineWidth, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay};
    public static final int[] N = {com.playfy.tv.R.attr.widthChange};
    public static final int[] O = {com.playfy.tv.R.attr.tabBackground, com.playfy.tv.R.attr.tabContentStart, com.playfy.tv.R.attr.tabGravity, com.playfy.tv.R.attr.tabIconTint, com.playfy.tv.R.attr.tabIconTintMode, com.playfy.tv.R.attr.tabIndicator, com.playfy.tv.R.attr.tabIndicatorAnimationDuration, com.playfy.tv.R.attr.tabIndicatorAnimationMode, com.playfy.tv.R.attr.tabIndicatorColor, com.playfy.tv.R.attr.tabIndicatorFullWidth, com.playfy.tv.R.attr.tabIndicatorGravity, com.playfy.tv.R.attr.tabIndicatorHeight, com.playfy.tv.R.attr.tabInlineLabel, com.playfy.tv.R.attr.tabMaxWidth, com.playfy.tv.R.attr.tabMinWidth, com.playfy.tv.R.attr.tabMode, com.playfy.tv.R.attr.tabPadding, com.playfy.tv.R.attr.tabPaddingBottom, com.playfy.tv.R.attr.tabPaddingEnd, com.playfy.tv.R.attr.tabPaddingStart, com.playfy.tv.R.attr.tabPaddingTop, com.playfy.tv.R.attr.tabRippleColor, com.playfy.tv.R.attr.tabSelectedTextAppearance, com.playfy.tv.R.attr.tabSelectedTextColor, com.playfy.tv.R.attr.tabTextAppearance, com.playfy.tv.R.attr.tabTextColor, com.playfy.tv.R.attr.tabUnboundedRipple};
    public static final int[] P = {com.playfy.tv.R.attr.textInputLayoutFocusedRectEnabled};
    public static final int[] Q = {R.attr.enabled, R.attr.textColorHint, R.attr.maxWidth, R.attr.minWidth, R.attr.hint, R.attr.maxEms, R.attr.minEms, com.playfy.tv.R.attr.boxBackgroundColor, com.playfy.tv.R.attr.boxBackgroundMode, com.playfy.tv.R.attr.boxCollapsedPaddingTop, com.playfy.tv.R.attr.boxCornerRadiusBottomEnd, com.playfy.tv.R.attr.boxCornerRadiusBottomStart, com.playfy.tv.R.attr.boxCornerRadiusTopEnd, com.playfy.tv.R.attr.boxCornerRadiusTopStart, com.playfy.tv.R.attr.boxStrokeColor, com.playfy.tv.R.attr.boxStrokeErrorColor, com.playfy.tv.R.attr.boxStrokeWidth, com.playfy.tv.R.attr.boxStrokeWidthFocused, com.playfy.tv.R.attr.counterEnabled, com.playfy.tv.R.attr.counterMaxLength, com.playfy.tv.R.attr.counterOverflowTextAppearance, com.playfy.tv.R.attr.counterOverflowTextColor, com.playfy.tv.R.attr.counterTextAppearance, com.playfy.tv.R.attr.counterTextColor, com.playfy.tv.R.attr.cursorColor, com.playfy.tv.R.attr.cursorErrorColor, com.playfy.tv.R.attr.endIconCheckable, com.playfy.tv.R.attr.endIconContentDescription, com.playfy.tv.R.attr.endIconDrawable, com.playfy.tv.R.attr.endIconMinSize, com.playfy.tv.R.attr.endIconMode, com.playfy.tv.R.attr.endIconScaleType, com.playfy.tv.R.attr.endIconTint, com.playfy.tv.R.attr.endIconTintMode, com.playfy.tv.R.attr.errorAccessibilityLiveRegion, com.playfy.tv.R.attr.errorContentDescription, com.playfy.tv.R.attr.errorEnabled, com.playfy.tv.R.attr.errorIconDrawable, com.playfy.tv.R.attr.errorIconTint, com.playfy.tv.R.attr.errorIconTintMode, com.playfy.tv.R.attr.errorTextAppearance, com.playfy.tv.R.attr.errorTextColor, com.playfy.tv.R.attr.expandedHintEnabled, com.playfy.tv.R.attr.helperText, com.playfy.tv.R.attr.helperTextEnabled, com.playfy.tv.R.attr.helperTextTextAppearance, com.playfy.tv.R.attr.helperTextTextColor, com.playfy.tv.R.attr.hintAnimationEnabled, com.playfy.tv.R.attr.hintEnabled, com.playfy.tv.R.attr.hintMaxLines, com.playfy.tv.R.attr.hintTextAppearance, com.playfy.tv.R.attr.hintTextColor, com.playfy.tv.R.attr.passwordToggleContentDescription, com.playfy.tv.R.attr.passwordToggleDrawable, com.playfy.tv.R.attr.passwordToggleEnabled, com.playfy.tv.R.attr.passwordToggleTint, com.playfy.tv.R.attr.passwordToggleTintMode, com.playfy.tv.R.attr.placeholderText, com.playfy.tv.R.attr.placeholderTextAppearance, com.playfy.tv.R.attr.placeholderTextColor, com.playfy.tv.R.attr.prefixText, com.playfy.tv.R.attr.prefixTextAppearance, com.playfy.tv.R.attr.prefixTextColor, com.playfy.tv.R.attr.shapeAppearance, com.playfy.tv.R.attr.shapeAppearanceOverlay, com.playfy.tv.R.attr.startIconCheckable, com.playfy.tv.R.attr.startIconContentDescription, com.playfy.tv.R.attr.startIconDrawable, com.playfy.tv.R.attr.startIconMinSize, com.playfy.tv.R.attr.startIconScaleType, com.playfy.tv.R.attr.startIconTint, com.playfy.tv.R.attr.startIconTintMode, com.playfy.tv.R.attr.suffixText, com.playfy.tv.R.attr.suffixTextAppearance, com.playfy.tv.R.attr.suffixTextColor};
    public static final int[] R = {R.attr.textAppearance, com.playfy.tv.R.attr.enforceMaterialTheme, com.playfy.tv.R.attr.enforceTextAppearance};
}
